GET http://127.0.0.1:8000/api/memes/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/memes/random
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/memes/?file_name=everythings-cool-in-dobby-club
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/series/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/series/?series_number=1
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/actors/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/actors/?first_name=David&last_name=Mitchell
Content-Type: application/json


###

GET http://127.0.0.1:8000/api/actors/?last_name=Webb
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/locations/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/locations/?name=JLB
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/scripts/1/2
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/characters/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/characters/?first_name=mark
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/quotes/search/?quote=fuck
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/quotes/filter/?spoken_by=dobby
Content-Type: application/json


###

GET http://127.0.0.1:8000/api/quotes/random/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/audio/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/audio/?file_name=porn
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/audio/random/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/avatars/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/avatars/?file_name=andy
Content-Type: application/json


###

GET http://127.0.0.1:8000/api/avatars/random/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/episodes/
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/episodes/?series=2
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/episodes/?start_date=2003-09-24&end_date=2015-11-26
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/episodes/?start_date=2015-01-01
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/episodes/?title=Quantocking
Content-Type: application/json